In [1]:
import numpy as np

In [2]:
data = np.random.randn(2, 3)
data

array([[-0.45684319, -3.01944698, -0.19437043],
       [-0.74548421,  1.59394585, -0.60331313]])

In [3]:
data * 10

array([[ -4.5684319 , -30.19446976,  -1.94370428],
       [ -7.45484213,  15.9394585 ,  -6.03313134]])

In [4]:
data + data

array([[-0.91368638, -6.03889395, -0.38874086],
       [-1.49096843,  3.1878917 , -1.20662627]])

In [5]:
data.shape

(2, 3)

In [6]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [7]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[6]

6

In [9]:
arr[5:8]

array([5, 6, 7])

In [10]:
data[1][0]

-0.745484212542276

In [11]:
data.T

array([[-0.45684319, -0.74548421],
       [-3.01944698,  1.59394585],
       [-0.19437043, -0.60331313]])

In [12]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [14]:
data2 = np.random.rand(2, 3)
data2

array([[0.23291334, 0.65707961, 0.23409738],
       [0.28609831, 0.38072988, 0.53546184]])

In [15]:
data3 = np.maximum(data, data2)
data3

array([[0.23291334, 0.65707961, 0.23409738],
       [0.28609831, 1.59394585, 0.53546184]])

In [16]:
print(data3.sum())
print(data3.mean())
print(data3.cumprod())

3.5395963223091904
0.5899327203848651
[0.23291334 0.15304261 0.03582687 0.01025001 0.01633796 0.00874835]


In [17]:
data.sort()
data

array([[-3.01944698, -0.45684319, -0.19437043],
       [-0.74548421, -0.60331313,  1.59394585]])

In [18]:
data.sum()

-3.425512091201136

In [19]:
import pandas as pd
import sqlite3 as sql


In [20]:
df_cardio = pd.read_json(' cardio.json')
df_cardio 



FileNotFoundError: File  cardio.json does not exist