In [1]:
import numpy as np

In [2]:
data = np.random.randn(2, 3)
data

array([[ 1.13126559, -0.20697134, -0.85135393],
       [-0.16088241, -1.5376406 ,  0.20771048]])

In [3]:
data * 10

array([[ 11.31265594,  -2.06971337,  -8.51353932],
       [ -1.60882407, -15.37640604,   2.07710479]])

In [4]:
data + data

array([[ 2.26253119, -0.41394267, -1.70270786],
       [-0.32176481, -3.07528121,  0.41542096]])

In [5]:
data.shape

(2, 3)

In [6]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [7]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[6]

6

In [9]:
arr[5:8]

array([5, 6, 7])

In [10]:
data[1][0]

-0.1608824072271882

In [11]:
data.T

array([[ 1.13126559, -0.16088241],
       [-0.20697134, -1.5376406 ],
       [-0.85135393,  0.20771048]])

In [12]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [14]:
data2 = np.random.rand(2, 3)
data2

array([[0.77528567, 0.55401417, 0.76989397],
       [0.56814764, 0.08008058, 0.04070783]])

In [15]:
data3 = np.maximum(data, data2)
data3

array([[1.13126559, 0.55401417, 0.76989397],
       [0.56814764, 0.08008058, 0.20771048]])

In [16]:
print(data3.sum())
print(data3.mean())
print(data3.cumprod())

3.3111124332816555
0.5518520722136092
[1.13126559 0.62673717 0.48252117 0.27414326 0.02195355 0.00455998]


In [17]:
data.sort()
data

array([[-0.85135393, -0.20697134,  1.13126559],
       [-1.5376406 , -0.16088241,  0.20771048]])

In [18]:
data.sum()

-1.4178722064204923

In [19]:
import pandas as pd
import sqlite3 as sql
