In [1]:
import numpy as np

In [2]:
data = np.random.randn(2, 3)
data

array([[ 0.85220999,  0.52939634, -0.73228663],
       [ 0.00704102,  0.08159906, -1.39468127]])

In [3]:
data * 10

array([[  8.52209993,   5.29396342,  -7.32286628],
       [  0.07041022,   0.81599065, -13.94681268]])

In [4]:
data + data

array([[ 1.70441999,  1.05879268, -1.46457326],
       [ 0.01408204,  0.16319813, -2.78936254]])

In [5]:
data.shape

(2, 3)

In [6]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [7]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[6]

6

In [9]:
arr[5:8]

array([5, 6, 7])

In [10]:
data[1][0]

0.007041021976745075

In [11]:
data.T

array([[ 0.85220999,  0.00704102],
       [ 0.52939634,  0.08159906],
       [-0.73228663, -1.39468127]])

In [12]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [14]:
data2 = np.random.rand(2, 3)
data2

array([[0.92839884, 0.2258637 , 0.57746503],
       [0.1063192 , 0.91394481, 0.5773876 ]])

In [15]:
data3 = np.maximum(data, data2)
data3

array([[0.92839884, 0.52939634, 0.57746503],
       [0.1063192 , 0.91394481, 0.5773876 ]])

In [16]:
print(data3.sum())
print(data3.mean())
print(data3.cumprod())

3.632911823590769
0.6054853039317948
[0.92839884 0.49149095 0.28381884 0.03017539 0.02757864 0.01592357]


In [17]:
data.sort()
data

array([[-0.73228663,  0.52939634,  0.85220999],
       [-1.39468127,  0.00704102,  0.08159906]])

In [18]:
data.sum()

-0.6567214737786187

In [19]:
import pandas as pd
import sqlite3 as sql


In [22]:
df_cardio = pd.read_json(' cardio.json')
df_cardio 



FileNotFoundError: File  cardio.json does not exist